# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: bulid

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.py'
          upload_exe_with_name: 'srultoolbox'
          options: --onefile, --name "srultoolbox", --windowed, --add-data "apks;apks"
#  pyinstaller-build-linux:
#    runs-on: linux-latest
#    steps:
#      - name: Create Executable
#        uses: sayyid5416/pyinstaller@v1
#        with:
#          python_ver: '3.12'
#          spec: 'main.py'
#          upload_exe_with_name: 'srultoolbox'
          options: --onefile, --name "srultoolbox", --windowed, --add-data "apks:apks"
  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.py'
          upload_exe_with_name: 'srultoolbox'
          options: --onefile, --name "srultoolbox", --windowed, --add-data "apks:apks"
